export enum catalogActionTypes {
	FETCH_PRODUCTS = '@@catalog/FETCH_PRODUCTS',
	TOGGLE_IS_FETCHING = '@@catalog/TOGGLE_IS_FETCHING',
	ADD_MESSAGE = '@@message/ADD_MESSAGE',
	REMOVE_MESSAGE = '@@message/REMOVE_MESSAGE',
	SET_VISIBILITY = '@@message/SET_VISIBILITY',
	FETCH_ERROR = '@@catalog/FETCH_ERROR',
	ADD_TO_CART = '@@cart/ADD_TO_CART',
	REMOVE_FROM_CART = '@@cart/REMOVE_FROM_CART'
}
